### ISSUE TITLE
Update copyright status

### ISSUE THREAD

**Issue by kcrisman** [dandrake/sagetex#26]
There are a number of references to @dandrake personally still existing.  Which made sense for 3.0, but now with the "maintainer" situation probably that should be updated somehow.  If Dan just transferred copyright to SageMath developers maybe that would take care of it?  At any rate this isn't essential for making changes for SageTeX within Sage, but probably should nonetheless be taken care of eventually.   Similarly, there are some old references to Dan's website which are certainly outdated.

I am hesitant to do those changes as a PR though without knowing more about the status.  So this issue keeps track of that.

**Comment by dimpase** [comment]
I've cleaned few of these up already, specifying that the current maintainers are Sagemath devs.

**Comment by dimpase** [comment]
the old bitbucket repo seems to be just gone. Still in Google's cache, dated 2018/11

**Comment by dimpase** [comment]
47a2f1f7248513d6a9cf956d7999386130bcc97f removes the remaining dead link.

**Comment by dandrake** [comment]
I'm perfectly willing to assign copyright to Sagemath devs. How should I do that? And can I just assign it to "Sagemath developers"? To Sagemath-the-company?

**Comment by kcrisman** [comment]
Thanks, @dandrake !  

Presumably the company is something quite different.  Probably Sagemath developers is fine? @dimpase any thoughts?

**Comment by dimpase** [comment]
IMHO it would do to add Sagemath devs as copyright holders, no need to reassigning anything. After all, we are not going to change the licence.

 I'd formulate it something as `sagetex written primarily by Dan Drake, with extra additions from persons listed in CONTRIBUTORS. Currently maintained by SageMath developers`.

**Comment by kcrisman** [comment]
This sounds very reasonable.
