### ISSUE TITLE
Does version number matter?

### ISSUE THREAD

**Issue by kcrisman** [dandrake/sagetex#27]
Typically there are warnings issued when there is an upgrade and one doesn't upgrade one's `sagetex.sty` file, but this doesn't appear to be happening with 3.1 and 3.2.  This issue is for investigating this.  

Most likely it would simply involve updating the two lines that currently have `2015/08/26 v3.0-92d9f7a` in `sagetex.dtx` (currently lines 32 and 35, as of commit 7ded091).  (Along the same lines, the `\changes` probably should be updated in that file, as that presumably is used somewhere.)

Relevant warnings in various documentation:

`sagetex.dtx`:
```
% As of version 2.2.4, \ST automatically checks to see if the versions
% of the style file and Python module match. This is intended to prevent
% strange version mismatch problems, but if you would like to use
% mismatched sources, you can---at your peril---give the
% |noversioncheck| option when you load the \ST package. Don't be
% surprised if things don't work when you do this.
%
% If you are considering using this option because the Sage script
% complained and exited, you really should just get the \LTX and Python
% modules synchronized. Every copy of Sage since version 4.3.2 comes
% with a copy of |sagetex.sty| that is matched up to Sage's baked-in \ST
% support, so you can always use that. See the
% \href{http://doc.sagemath.org/html/en/tutorial/sagetex.html}{\ST section of the Sage
%   tutorial}.
```
At http://doc.sagemath.org/html/en/tutorial/sagetex.html
```
Warning it’s very important that the file sagetex.sty that LaTeX uses when typesetting your document match the version of SageTeX that Sage is using. If you upgrade your Sage installation, you really should delete all the old versions of sagetex.sty floating around.
Because of this problem, we recommend copying the SageTeX files into your home directory’s texmf directory (the third method above). Then there is only one thing you need to do (copy a directory) when you upgrade Sage to insure that SageTeX will work properly.
```

**Comment by dimpase** [comment]
I believe I've tracked down all the places where the version is set - two in sagetex.dtx and one in setup.py
I think we should write up release instructions and commit them into this repo.

**Comment by kcrisman** [comment]
> I think we should write up release instructions and commit them into this repo.

Yes, also regarding making sure people put the pdfs as in Sage Trac 22499.  Good.

**Comment by dimpase** [comment]
release process documented by 2fa350b5d726e4a6fb0dc8b13fe3c608238201d7

**Comment by kcrisman** [comment]
Sorry, what I meant was "yes, you did also document that part" but apparently I should have written a sentence with a verb.
