### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by isuruf** [dandrake/sagetex#40]
sagemath license file says sagetex GPLv2+ (CC BY-SA 3.0 for included documentation)
Could you add a license file and copyright notices?

**Comment by dimpase** [comment]
PR please...

**Comment by kcrisman** [comment]
At the same time in such a PR, we should update the time on this, it still says 2015 I think - I am pretty sure we had a discussion somewhere (public) that ensued in Dan transferring copyright to SageMath developers (or something like that).

**Comment by dandrake** [comment]
For what it's worth, I'll iterate that it was my intent to transfer
ownership to the SageMath organization, so it's fine with me if you update
the license.

**Comment by dimpase** [comment]
resolved by https://github.com/sagemath/sagetex/commit/6dbe41ac3c2e97f3b766914a727cded51854efd4
